export const SET_BASE_INFO = 'SET_BASE_INFO';
export const SET_ATTENDANCE = 'SET_ATTENDANCE';

export const SET_DEADLINES = 'SET_DEADLINES';
export const SET_DEADLINES_FILTER = 'SET_DEADLINES_FILTER';

export const SET_EVENTS = 'SET_EVENTS';
export const SET_EVENTS_FILTER = 'SET_EVENTS_FILTER';

export const SET_AVERAGE_GRADE = 'SET_AVERAGE_GRADE';
export const SET_DAYS_WITHOUT_BAD_GRADES = 'SET_DAYS_WITHOUT_BAD_GRADES';

export const SET_STUDENT_WORKLOAD = 'SET_STUDENT_WORKLOAD';
